---
apiVersion: apps.oam.cfcn.io/v1beta1
kind: Application
metadata:
  name: web-saas
spec:
  applicationName: web-saas
  cloud:
    aws:
      ec2: "true"
      s3: "true"
    azure:
      blob: "true"
      vm: "true"
    gcp:
      gke: "true"
      vm:
        enabled: "true"
        size: n1-standard-1
  k8s:
    monitor: "true"
    prometheus: "true"
    statefulset:
      image: "redis:latest"
      replicas: 3
