name: "Manifests Lint"

on:
  push:
    paths:
    - 'config/samples/**'
    branches:
      - master
  pull_request:

jobs:
  validate:
    name: "Install pip"
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '2'
       
      - name: Git Install
        run: yum install git -y
     
      - name: Git Diff
        run: git diff HEAD^ HEAD

      - name: Install Python3 
        id: python3
        run: yum install python36 -y

      - name: Install pyyaml
        id: yamlint
        run: pip3 install yamllint || true
          
      - name: Validate Yaml
        id: vyaml
        if: github.event_name == 'pull_request'
        run: yamllint --no-warnings config/samples/* 
        continue-on-error: false
  
  deploy:
    name: deploy-manifests
    runs-on: self-hosted
    needs: validate
    steps:      
      - id: success
        if: github.ref == 'refs/heads/master' && github.event_name == 'push' 
        run: echo "Deployment successfull"

